### ISSUE TITLE
Cannot read properties of undefined (reading 'app')

### ISSUE THREAD

**Issue by onlyhy** [mark-when/vue-view-template#1]
Hello,
After running  `npm run dev`, I got this result :
`Cannot read properties of undefined (reading 'app')  at markwhenStore.ts:31:46`

Looking forward to your help!
Thanks!

**Comment by kochrt** [comment]
What was the issue? Do I need to update the documentation?

Let me know if you have other issues or how things go, I want to make sure custom visualizations work well!
